### ISSUE TITLE
'Share' option Qobuz to play in LMS

### ISSUE THREAD

**Issue by Alex541lkin** [CDrummond/lms-material-app#10]
Since the last update 'share' from native Qobuz app doesn't work correctly. HTTP Link shows in Queue instead of playlist with tracks. Please 🙏 fix this. Thank you! 
![Screenshot_2023-03-16-20-13-58-982_com craigd lmsmaterial app](https://user-images.githubusercontent.com/128075872/225699483-905d72ca-0033-4ec8-9be8-83424843225e.jpg)

**Comment by CDrummond** [comment]
All this app does is pass the URL to LMS. If it worked before but not now then the issue is in LMS. Its up to LMS to handle this URL, the app just forwards it on.

**Comment by CDrummond** [comment]
Looks like an LMS or plugin issue: https://forums.slimdevices.com/forum/user-forums/3rd-party-software/94305-qobuz-com-streaming-plugin?p=1634045#post1634045

**Comment by Alex541lkin** [comment]
Yes, it was my post there, now fixed, works again - thanks for the head up!

пт, 17 мар. 2023 г., 10:10 CraigD ***@***.***>:
