### ISSUE TITLE
Changes made under Interface aren't being applied

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material-app#11]
Changes made under Interface aren't being applied when on the app. Works fine in the web browser, and I believe it worked on the last version of the app. Not sure what further info I can provide, but I'll provide what I can

**Comment by CDrummond** [comment]
Just tried, and changes are applied. All bar 'Application' settings happen within the embedded browser, so work just as if a regular browser was used - all the app does is load the skin into 'WebView' (which is an embeddable version of the chrome backend).
