### ISSUE TITLE
Duplicate json request when seeking

### ISSUE THREAD

**Issue by robho** [CDrummond/lms-material-app#12]
When I seek inside a song there are two "time" requests sent to the server. They're not always identical, the "time" parameter sometimes differ by a second.

I guess it shouldn't be a problem to send two requests, but there's something wrong in LMS (server, perl code) which causes seeks to fail for ogg and opus if two seeks are performed "at the same time".

I'll take a look at the LMS (server) issue, but wanted to get an opinion on the double time requests. Are they deliberate? Are they caused by the touch handling in the app?

I'm running the F-Droid version of the app and have tried this on different Android devices. I don't see a problem with the normal "PC version" of the material UI so maybe this is a touch issue..

**Comment by CDrummond** [comment]
This has nothing to do with this APK. This is the skin that is sending these events, The APK is just a simple WebView wrapper!

Moved to https://github.com/CDrummond/lms-material/issues/672
