### ISSUE TITLE
Light, Dark, Darker, (Darkest), Black Theme settings 

### ISSUE THREAD

**Issue by artatgray** [CDrummond/lms-material-app#14]
Hi devs,

I like to propose a Darkest theme option under the Interface settings. This would not be a replacement of Black or Darker, just another option. 

In the screenshot below, we've got the Darker theme in the LMS app:
![Screenshot_2023-06-30-19-29-48-43_b34bcfd62110e2ea2eb7c00873abebbe](https://github.com/CDrummond/lms-material-app/assets/104296517/4bcca2d2-172f-4ac0-bf00-34a7f821dbc6)

The following screenshot, from another app, is an example of what I'd like to see when specifying a Darkest theme. It's not black, by the way, just a shade of very dark gray:

![Screenshot_2023-06-30-19-29-42-96_5a95cb7a76adf25e43f1cd66aca96a7a](https://github.com/CDrummond/lms-material-app/assets/104296517/5f65ffec-6df9-465f-81d5-b2f3bb1da205)

Thanks in advance,
Bill

**Comment by CDrummond** [comment]
This is a skin requuest, not app - the skin controls themes, colours, etc.

Not sure I see the use of yet another dark variant. However, you can install your own themes - see https://github.com/CDrummond/lms-material/wiki/07-Customisation

Closinf this as its not applicable to this APK.
