### ISSUE TITLE
Add support for MediaControls api on android

### ISSUE THREAD

**Issue by pacjo** [CDrummond/lms-material-app#17]
(I was about to open the issue over at [squeezelite](https://github.com/ralph-irving/squeezelite/), but I think it's better to it it here.)

Having ability to control audio from [MediaControls](https://developer.android.com/media/implement/surfaces/mobile) would be a welcome addition to the app. I hope it's possible to implement.

related to #5

**Comment by CDrummond** [comment]
As you stated, related to #5 - and not going to be implemented for the same reasons. Also discussed on forums:

https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1668548#post1668548

Note, as per the description, this is a **simple** WebView wrapper.

When the skin is used via Chrome, then it can show a notification like this - but it hacks it by playing 10second silent track in a loop.

**Comment by pacjo** [comment]
Ok, thanks

**Comment by CDrummond** [comment]
FWIW, next release (0.6.0) uses MediaSession API.
