### ISSUE TITLE
very fast 404 error screen when material is missing from server

### ISSUE THREAD

**Issue by clach04** [CDrummond/lms-material-app#18]
If the app is installed and pointed at LMS BUT Material (https://github.com/CDrummond/lms-material) plugin has not been installed a 404 page is shown for a fraction of a second then disappears. It is easy to miss this.

Be nice enhancement/usability change if 404s were caught by the application and a toast/message displayed that Material was not found on the server.

Thanks for this app! Works great!

**Comment by CDrummond** [comment]
You are taken to the config page! Sorry, but this is as designed.
