### ISSUE TITLE
Permission denied when starting Squeezelite if app is copied between devices

### ISSUE THREAD

**Issue by mavit** [CDrummond/lms-material-app#19]
I recently got a new Android phone, and used its setup wizard to copy apps and settings from my old phone.  This exposed a couple of problems, one of which is:

When I tried to start Termux Squeezelite on the new device, I got a permission denied error rather than being prompted to grant the permission to allow this.  I worked around this by setting the player to None and then setting it back to Squeezelite, to cause me to be re-prompted.

**Comment by CDrummond** [comment]
Next release will check permissions at start and re-set config items if not granted.
