### ISSUE TITLE
Top navigation bar is colliding with Notiifcation Area on Pixel 4a 5g - CalyxOS, even after 0.6.2 update

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material-app#27]
Finally updated to the 0.6 line of updates, and am having collisions with the top of LMS and my phone's Notification Area. I updated to 0.6.2 to see if that would fix the problem, but no dice. I'm only able to access Volume/Info/Menu by pressing right at the bottom of the respective areas. The collision also is causing the player icons to be completely covered by my phone's camera cutout (it's quite comical, actually).

Info: App 0.6.2
Phone: Pixel 4a 5g
Os: Calyx OS 5.9.0
Android Version: 14
LMS Material: 5.2.1

Screenshot included. Camera notch not included (use your imagination 😉)

Will gladly provide other info/test things if needed

Edit: Also, forgot to mention. I'm on the latest version of the Material Skin, and "Fullscreen" is set to "OFF" in Applications Settings.

![Screenshot_20240809-165246](https://github.com/user-attachments/assets/6af21bc9-d2b8-482c-8b8d-ac82783fea48)

**Comment by cirdanlunae** [comment]
I was browsing the Lyrion Forums, and happened upon this response from you to someone else. Is this the same issue I'm seeing? If so, then ignore this issue, since it seems you're aware. Also, in the future, do you prefer Github Issues or Forum responses for letting you know about bugs more?

https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1721048#post1721048

**Comment by CDrummond** [comment]
I actually prefer issues here, as it groups the info together - plus less chance of it being forgotten! However, posting on the forum is fine - I read it often. Feel free to post links on forum to here, and vice versa.
