### ISSUE TITLE
Strange and messy immersive mode 

### ISSUE THREAD

**Issue by markusschloesser** [CDrummond/lms-material-app#28]
0.6 and 0.6.2 do a strange immersive mode, where I can't reach the top anymore.
![Screenshot_20240811-223852.png](https://github.com/user-attachments/assets/672c85e4-f97e-4f04-a937-b52dd1df59e7)

Pixel 8 pro, android 14

For now I reverted back to 0.5
Btw thank you for the app! Appreciate it 😊

**Comment by CDrummond** [comment]
Please update MaterialSkin, and refresh the cache.
