### ISSUE TITLE
Display over statusbar

### ISSUE THREAD

**Issue by uudruid74** [CDrummond/lms-material-app#33]
For some reason, this app displays its top header info on top of my status bar.  Its the only app that does this.  It also defaults to a destination server that I need to change and touching that high on the screen near the status bar drops down notifications.  Its almost impossible to use.

![Screenshot_2024-09-08-18-22-09-42_b34bcfd62110e2ea2eb7c00873abebbe](https://github.com/user-attachments/assets/42ab6438-b088-4426-b596-63b6dba2e8b7)

**Comment by CDrummond** [comment]
Please update MaterialSkin, and refresh the cache.

**Comment by CDrummond** [comment]
No more info, and as stated needs updated Skin.
