### ISSUE TITLE
Deactivating "Fullscreen" adds unnecassary margin at the bottom

### ISSUE THREAD

**Issue by chrober** [CDrummond/lms-material-app#34]
I am using version 0.8.2 on a Samsung Galaxy S20.
I have set my navigation bar to "swipe gestures", so there is no visible navigation bar on my phone.

When I deactivate the "Fullscreen" option in the Lyrion app, I get an unnecassary margin at the bottom of the screen, which does not look too nice (see screenshot).
![Screenshot_20241020_125539_Lyrion](https://github.com/user-attachments/assets/a9d2095b-3602-4a8e-ab16-b793e96706c4)

I guess this is the space where the Lyrion app would assume the navigation bar. Is there any chance to get this "fixed", i.e. having the app respecting the actual height of the navigation bar (which is zero on my device)?

I actually don't want to use the fullscreen option since I want to have the status bar on the top of the screen visible.

**Comment by CDrummond** [comment]
You sway when you "deactivate" fullscreen - so does the error only occur when you toggle this? i.e. if you disable fullscreen, quit the app, and restart - is everything then OK?

I don;t use fullscreen, but do use gesture navigation, and this works for me - but I have a white bar bottom middle, which is missing from your screenshot.

**Comment by chrober** [comment]
> You sway when you "deactivate" fullscreen - so does the error only occur when you toggle this? i.e. if you disable fullscreen, quit the app, and restart - is everything then OK?

No. The issue persists. If I quit/restart the Lyrion app with fullscreen already activated the margin is still there.

> I don;t use fullscreen, but do use gesture navigation, and this works for me - but I have a white bar bottom middle, which is missing from your screenshot.

These are my Android Navigation Bar settings:
![Screenshot_20241021_123724_Settings](https://github.com/user-attachments/assets/756897e6-f4b5-4181-ae19-220cb3969637)

Probably the deactivated "Gesture hints" is why I am missing the white bar at the bottom? This is what it looks like if I have "gesture hints" enabled:
![Screenshot_20241021_124242_Lyrion](https://github.com/user-attachments/assets/860ad03c-739d-4c77-961b-92d204fdafa3)

**Comment by chrober** [comment]
This is how it looks like if I set my Android navigation bar to "Buttons":
![Screenshot_20241021_124706_Lyrion](https://github.com/user-attachments/assets/f0056d8d-bce0-4e1a-aaaa-b103a70c9b1f)

**Comment by CDrummond** [comment]
Which android version is this? As I use gesture navigation, and I've never seen this weird hybrid type you seem to have.

**Comment by CDrummond** [comment]
OK, just seen this setting. Must admit I find it awful! Not sure why you would use this as opposed to "swipe from sides and bottom"...

**Comment by chrober** [comment]
> Which android version is this? As I use gesture navigation, and I've never seen this weird hybrid type you seem to have.

It's running the latest stock software that Samsung has provided for this device and it's based on Android 13.

> OK, just seen this setting. Must admit I find it awful! Not sure why you would use this as opposed to "swipe from sides and bottom"...

I also have an option to switch to the "swipe from sides and bottom" mode. However, swiping from sides has never worked for me on this device.

**Comment by CDrummond** [comment]
Would you mind testing the attached APK? It's placed within a ZIP as GitHub will not allow uploading APKs :(

[test.zip](https://github.com/user-attachments/files/17604271/test.zip)

**Comment by chrober** [comment]
> Would you mind testing the attached APK?

Sure! Will test it tomorrow. (Not enough time today.)

**Comment by chrober** [comment]
Just tested your version 0.8.3.
It looks much better now!
There is still some bottom margin which might be reduced a bit more, bit it defintely looks more appealing now.
Here are two screenshots, one without navigation hints (which is my personal default setting), the other one with navigation hints:
![Screenshot_20241103_131544_Lyrion](https://github.com/user-attachments/assets/ffd6cc67-effc-45e9-9cfa-bab91c4cef55) ![Screenshot_20241103_131627_Lyrion](https://github.com/user-attachments/assets/c5b8d041-85d0-40ca-9185-cd2dcdf46d14)

Thank you!

**Comment by CDrummond** [comment]
Try this version...
[test.2.zip](https://github.com/user-attachments/files/17611129/test.2.zip)

**Comment by chrober** [comment]
Awesome! This is how it looks with your latest build (please ignore the pixelated look of the screenshots):
![Screenshot_20241103_183154_Lyrion](https://github.com/user-attachments/assets/a536993b-c5f2-4868-a7d3-1a27a91791da) 
![Screenshot_20241103_183224_Lyrion](https://github.com/user-attachments/assets/19c94ae7-1da4-423e-a095-177f5d62288c) 
![Screenshot_20241103_183244_Lyrion](https://github.com/user-attachments/assets/6cb2e783-8127-49dc-81ec-5dc17c6e88bf)

**Comment by CDrummond** [comment]
Great! I'll close this now, and will tag a new release soon...
