### ISSUE TITLE
Players do not resume when call ends

### ISSUE THREAD

**Issue by dbrand666** [CDrummond/lms-material-app#4]
I have the `During phone call` setting set to `Pause all active players` and they do pause when I'm on the phone but they don't resume when I end the call. Would that be possible?

**Comment by CDrummond** [comment]
There is code to handle the call ending, and it should resume them. Although this is not a feature I use, or actually see the benefit of.

Have you tried the other options? i.e. Pausing current? Mute all? Mute current? Do any of these work?

What Android version are you on?

**Comment by dbrand666** [comment]
I've tried all the options. They all stop the music but none of them resume when the call ends.

I'm on the latest (January 2023) stock android 13 on a Pixel 7.

P.S. This isn't a priority for me either honestly. Just something I noticed.

**Comment by CDrummond** [comment]
Next release uses CallStateListener / PhoneStateListener to handle calls - so should fix this.
