### ISSUE TITLE
not listed in F-DROID app

### ISSUE THREAD

**Issue by jsmdy** [CDrummond/lms-material-app#41]
I've an updated version of F-DROID with an updated default repo, "Lyrion" doesn't appear on it, just LMS version 0.4.2 :(. 
Hopefully I install the apk but it can be useful to have it on Fdroid for future update of your wonderful app :).
I don't get why all seems ok on https://f-droid.org/packages/com.craigd.lmsmaterial.app/

**Comment by CDrummond** [comment]
Not sure what's wrong on your system, but I have just uninstalled the APK and re-installed 0.8.4 from f-droid.
