### ISSUE TITLE
Support for Android 13 media player

### ISSUE THREAD

**Issue by eengnr** [CDrummond/lms-material-app#5]
Hi, thanks a lot for your app and the Material skin!

Would it be possible to support the media player of Android 13, i.e. show the widget in the notifications like Squeeze Ctrl does?

**Comment by CDrummond** [comment]
The APK already shows a notification. As stated in the app itself, this will not show track info - as when the app is not shown the Javascript is "paused", to save battery.

Thius still works on my S210FE with Android 13

**Comment by eengnr** [comment]
Sure, I know that the APK shows a notification, but it's not the "native" media player from Android 13 :)
To have this native media player notification active, I still need Squeeze Ctrl which makes your LMS app kind of obsolete. Although searching/browsing through the music is better with your LMS app.
The only thing missing is this media player notification.
But if it's technically not possible to update the progress bar because the Javascript is paused, then I can understand why this workaround with the "app internal" notification is necessary.
